### PR TITLE
Pitch shifting

### PR DESCRIPTION
**Pull request by richtier**
These nodes seem undocumented. Should they be documented?
- LFO
- EnvelopeFollower

I assumed SemVer is used hence the version is now 1.1.0. If it is SemVer I will add that to CONTRIBUTE.md

todo:
 * [x] Add tests
 * [x] Update docs

https://www.youtube.com/watch?v=VyBOoVAmOfI

### CODE REVIEW

**Comment by Theodeus** [comment]
What algorithm is this implementation based on? I'm trying to pitch shift a pure sine wave but I'm getting very unnatural results,, 

I kinda like the results, when applied to a human voice, though it sounds more like a robot voice effect than a pitch shifter. :)

Maybe I need to tweak the settings somehow? Does it work on mono and stereo sources?

**Comment by richtier** [comment]
@Theodeus 

> What algorithm is this implementation based on?
A snippet that I found and repurposed to my needs about a year ago, I can hunt it down for context if that is helpful.

> Maybe I need to tweak the settings somehow? Does it work on mono and stereo sources?
Mono only as the audio I was working with was single channel. If stereo is required then I'm happy to add stereo support.

**Comment by richtier** [comment]
@Theodeus I found the source - it's from [pitch-shifter.js](https://github.com/urtzurd/html-audio/blob/gh-pages/static/js/pitch-shifter.js)

It's MIT licenced

**Comment by richtier** [comment]
@Theodeus ping :)

I'll solve the conflicts soon

**Comment by Theodeus** [comment]
Ah, it does make sense then! :) 

Granular pitch shifting is bound to work poorly on a pure sine, I think. It would be nice with stereo support though! We should call it GranularPitchShifter too, in case we add a shifter based of phase vocoding later on (I think it'd be better to keep these separated rather than having a PitchShifter node with multiple modes).

**Comment by Theodeus** [comment]
Also, just wanted to say that I'm really excited about this! I'm currently on parental leave, so that's why I'm a little slow to respond at times. I had to get the failing tests fixed too before I got around to this, but I really appreciate the work you put in!

**Comment by richtier** [comment]
after a long hiatus doing DIY, I'm back in the game.

**Comment by richtier** [comment]
@Theodeus I know it's rich of me, given my two month hiatus...but "ping" :)

**Comment by richtier** [comment]
@Theodeus ahem 👋

**Comment by Theodeus** [comment]
👋 Sorry, lot's going on at home. :)

Neat updates! 🎉 

However - I don't think I can merge until stereo support is solved. Merging as-is would cause a lot of use cases break ("this pitch shifter sounds broken, Tuna sucks") that is hard to communicate, and adding something like a channel merger would be an unexpected side effect that could cause a lot of confusion ("why is my stereo file suddenly mono?").

I totally get that it might be beyond the work you're willing to put in for this, so just let me know, and I'll try to find some time in the future to have a look myself. :)

**Comment by richtier** [comment]
understood thanks :)

**Pull request closed without merging**
